# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'setu.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_setu(object):
    def setupUi(self, setu):
        if setu.objectName():
            setu.setObjectName(u"setu")
        setu.setEnabled(True)
        setu.resize(800, 600)
        self.about = QAction(setu)
        self.about.setObjectName(u"about")
        self.mess = QAction(setu)
        self.mess.setObjectName(u"mess")
        self.action = QAction(setu)
        self.action.setObjectName(u"action")
        self.save = QAction(setu)
        self.save.setObjectName(u"save")
        self.view = QAction(setu)
        self.view.setObjectName(u"view")
        self.copy = QAction(setu)
        self.copy.setObjectName(u"copy")
        self.web = QAction(setu)
        self.web.setObjectName(u"web")
        self.web2 = QAction(setu)
        self.web2.setObjectName(u"web2")
        self.a1 = QAction(setu)
        self.a1.setObjectName(u"a1")
        self.a2 = QAction(setu)
        self.a2.setObjectName(u"a2")
        self.a3 = QAction(setu)
        self.a3.setObjectName(u"a3")
        self.a4 = QAction(setu)
        self.a4.setObjectName(u"a4")
        self.a5 = QAction(setu)
        self.a5.setObjectName(u"a5")
        self.copya = QAction(setu)
        self.copya.setObjectName(u"copya")
        self.rsize = QAction(setu)
        self.rsize.setObjectName(u"rsize")
        self.rdir = QAction(setu)
        self.rdir.setObjectName(u"rdir")
        self.rset = QAction(setu)
        self.rset.setObjectName(u"rset")
        self.fava = QAction(setu)
        self.fava.setObjectName(u"fava")
        self.favo = QAction(setu)
        self.favo.setObjectName(u"favo")
        self.favc = QAction(setu)
        self.favc.setObjectName(u"favc")
        self.favd = QAction(setu)
        self.favd.setObjectName(u"favd")
        self.a6 = QAction(setu)
        self.a6.setObjectName(u"a6")
        self.sear = QAction(setu)
        self.sear.setObjectName(u"sear")
        self.uplog = QAction(setu)
        self.uplog.setObjectName(u"uplog")
        self.about_this = QAction(setu)
        self.about_this.setObjectName(u"about_this")
        self.clears = QAction(setu)
        self.clears.setObjectName(u"clears")
        self.idel = QAction(setu)
        self.idel.setObjectName(u"idel")
        self.favr = QAction(setu)
        self.favr.setObjectName(u"favr")
        self.checku = QAction(setu)
        self.checku.setObjectName(u"checku")
        self.opens = QAction(setu)
        self.opens.setObjectName(u"opens")
        self.centralwidget = QWidget(setu)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.img = QLabel(self.centralwidget)
        self.img.setObjectName(u"img")

        self.verticalLayout.addWidget(self.img)

        setu.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(setu)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 21))
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menu_2 = QMenu(self.menubar)
        self.menu_2.setObjectName(u"menu_2")
        self.menu_3 = QMenu(self.menubar)
        self.menu_3.setObjectName(u"menu_3")
        self.menu_4 = QMenu(self.menubar)
        self.menu_4.setObjectName(u"menu_4")
        self.menu_5 = QMenu(self.menubar)
        self.menu_5.setObjectName(u"menu_5")
        setu.setMenuBar(self.menubar)

        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menu.addAction(self.view)
        self.menu.addAction(self.copy)
        self.menu.addSeparator()
        self.menu.addAction(self.web)
        self.menu.addAction(self.web2)
        self.menu.addAction(self.sear)
        self.menu.addSeparator()
        self.menu.addAction(self.copya)
        self.menu.addSeparator()
        self.menu.addAction(self.idel)
        self.menu_2.addAction(self.a1)
        self.menu_2.addAction(self.a2)
        self.menu_2.addAction(self.a3)
        self.menu_2.addAction(self.a4)
        self.menu_2.addAction(self.a5)
        self.menu_2.addAction(self.a6)
        self.menu_3.addAction(self.rsize)
        self.menu_3.addAction(self.rdir)
        self.menu_3.addAction(self.clears)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.rset)
        self.menu_4.addAction(self.fava)
        self.menu_4.addAction(self.favo)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.favr)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.favd)
        self.menu_4.addAction(self.favc)
        self.menu_5.addAction(self.about_this)
        self.menu_5.addAction(self.uplog)
        self.menu_5.addSeparator()
        self.menu_5.addAction(self.checku)
        self.menu_5.addAction(self.opens)

        self.retranslateUi(setu)

        QMetaObject.connectSlotsByName(setu)
    # setupUi

    def retranslateUi(self, setu):
        setu.setWindowTitle(QCoreApplication.translate("setu", u"\u4e8c\u6b21\u5143\u56fe\u7247", None))
        self.about.setText(QCoreApplication.translate("setu", u"\u5173\u4e8e", None))
        self.mess.setText(QCoreApplication.translate("setu", u"\u56fe\u7247\u4fe1\u606f", None))
        self.action.setText(QCoreApplication.translate("setu", u"\u590d\u5236\u56fe\u7247\u94fe\u63a5", None))
        self.save.setText(QCoreApplication.translate("setu", u"\u4fdd\u5b58\u56fe\u7247", None))
        self.view.setText(QCoreApplication.translate("setu", u"\u67e5\u770b\u56fe\u7247\u4fe1\u606f", None))
        self.copy.setText(QCoreApplication.translate("setu", u"\u590d\u5236\u56fe\u7247\u94fe\u63a5", None))
        self.web.setText(QCoreApplication.translate("setu", u"\u4f7f\u7528\u672c\u5730\u67e5\u770b\u5668\u6253\u5f00\u56fe\u7247", None))
        self.web2.setText(QCoreApplication.translate("setu", u"\u6253\u5f00\u56fe\u7247\u7684\u7f51\u9875\u94fe\u63a5", None))
        self.a1.setText(QCoreApplication.translate("setu", u"http://www.dmoe.cc/random.php", None))
        self.a2.setText(QCoreApplication.translate("setu", u"https://api.dongmanxingkong.com/suijitupian/acg/1080p/index.php", None))
        self.a3.setText(QCoreApplication.translate("setu", u"https://api.ixiaowai.cn/api/api.php", None))
        self.a4.setText(QCoreApplication.translate("setu", u"https://api.mtyqx.cn/api/random.php", None))
        self.a5.setText(QCoreApplication.translate("setu", u"https://api.mtyqx.cn/tapi/random.php", None))
        self.copya.setText(QCoreApplication.translate("setu", u"\u590d\u5236API\u63a5\u53e3", None))
        self.rsize.setText(QCoreApplication.translate("setu", u"\u8c03\u6574\u56fe\u7247\u663e\u793a\u5927\u5c0f", None))
        self.rdir.setText(QCoreApplication.translate("setu", u"\u4fee\u6539\u4fdd\u5b58\u6587\u4ef6\u5939", None))
        self.rset.setText(QCoreApplication.translate("setu", u"\u6062\u590d\u9ed8\u8ba4\u8bbe\u7f6e", None))
        self.fava.setText(QCoreApplication.translate("setu", u"\u5c06\u5f53\u524d\u56fe\u7247\u6dfb\u52a0\u5230\u6536\u85cf", None))
        self.favo.setText(QCoreApplication.translate("setu", u"\u6253\u5f00\u6536\u85cf\u4e2d\u7684\u56fe\u7247", None))
        self.favc.setText(QCoreApplication.translate("setu", u"\u6e05\u7a7a\u6536\u85cf", None))
        self.favd.setText(QCoreApplication.translate("setu", u"\u5220\u9664\u6536\u85cf\u4e2d\u7684\u4e00\u9879", None))
        self.a6.setText(QCoreApplication.translate("setu", u"https://cloud.qqshabi.cn/api/acg/api.php", None))
        self.sear.setText(QCoreApplication.translate("setu", u"\u5728SauceNAO\u4e2d\u641c\u7d22\u56fe\u7247", None))
        self.uplog.setText(QCoreApplication.translate("setu", u"\u66f4\u65b0\u65e5\u5fd7", None))
        self.about_this.setText(QCoreApplication.translate("setu", u"\u5173\u4e8e\u6b64\u7a0b\u5e8f", None))
        self.clears.setText(QCoreApplication.translate("setu", u"\u6e05\u9664\u56fe\u7247\u7f13\u5b58", None))
        self.idel.setText(QCoreApplication.translate("setu", u"\u5220\u9664\u8fd9\u5f20\u56fe\u7247", None))
        self.favr.setText(QCoreApplication.translate("setu", u"\u91cd\u547d\u540d\u6536\u85cf", None))
        self.checku.setText(QCoreApplication.translate("setu", u"\u68c0\u67e5\u66f4\u65b0", None))
        self.opens.setText(QCoreApplication.translate("setu", u"\u5f00\u6e90\u72b6\u6001", None))
        self.img.setText("")
        self.menu.setTitle(QCoreApplication.translate("setu", u"\u56fe\u7247\u64cd\u4f5c", None))
        self.menu_2.setTitle(QCoreApplication.translate("setu", u"\u83b7\u53d6\u56fe\u7247", None))
        self.menu_3.setTitle(QCoreApplication.translate("setu", u"\u56fe\u7247\u8bbe\u7f6e", None))
        self.menu_4.setTitle(QCoreApplication.translate("setu", u"\u56fe\u7247\u6536\u85cf", None))
        self.menu_5.setTitle(QCoreApplication.translate("setu", u"\u5e2e\u52a9", None))
    # retranslateUi

